name: musa-620
channels:
  - defaults
  - conda-forge
  - pyviz
dependencies:
  - python=3.6
  - numpy
  - pandas
  - matplotlib=3.1.0
  - jupyter
  - ipython
  - pip
  - altair
  - seaborn
  - vega_datasets
  - notebook
  - vega
  - geopandas=0.5.1
  - descartes
  - cartopy
  - mapclassify
  - contextily=1.0rc2
  - pyviz::hvplot
  - pyviz::holoviews
  - pyviz::geoviews>1.6.2
  - rasterio
  - rasterstats
  - earthpy
  - requests
  - census
  - pip:
      - us
      - tweepy
      - textblob
      - nltk
      - carto2gpd
      - esri2gpd
