name: musa-620
channels:
  - defaults
  - conda-forge
  - pyviz
dependencies:
  - python=3.6
  - numpy
  - pandas
  - matplotlib=3.1.0
  - jupyter
  - ipython
  - pip
  - altair
  - seaborn
  - vega_datasets
  - notebook
  - vega
  - geopandas=0.5.1
  - descartes
  - cartopy
  - mapclassify
  - contextily=1.0rc2
  - defaults::bokeh>=1.3
  - pyviz::hvplot
  - pyviz::holoviews=1.12.6
  - pyviz::geoviews>1.6.2
  - conda-forge::xarray=0.14
  - pyviz::datashader
  - pyviz::param
  - pyviz::panel
  - rasterio
  - rasterstats
  - earthpy
  - requests
  - census
  - selenium
  - beautifulsoup4
  - geckodriver
  - python-chromedriver-binary=77.0.3865.40.0
  - imageio
  - intake
  - intake-parquet
  - intake-xarray
  - dask
  - fastparquet
  - python-snappy
  - pyarrow
  - s3fs
  - tqdm
  - pandana
  - osmnx
  - networkx
  - scikit-learn
  - flask
  - dash
  - pip:
      - us
      - tweepy
      - textblob
      - nltk
      - carto2gpd
      - esri2gpd
      - rio-toa
      - rioxarray
      - missingno
      - osm2gpd
      - jupyter-panel-proxy
